Summary:	V3D library
Summary(pl.UTF-8):	Biblioteka V3D
Name:		libv3d
Version:	0.1.14
Release:	3
License:	LGPL v2.1
Group:		Libraries
Source0:	http://wolfsinger.com/~wolfpack/packages/%{name}-%{version}.tar.bz2
# Source0-md5:	2b125509b0be8b87e0d7262ebd69346d
Patch0:		%{name}-soname.patch
URL:		http://freecode.com/projects/libv3d
BuildRequires:	OpenGL-devel
BuildRequires:	OpenGL-GLU-devel
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
The libv3d library is a IO library for the V3D file format, a 3D model
file generated by the modeller Vertex 3D Model Assembler (hence the
name V3D). It is used to read and write V3D data to/from file and
memory with integrated OpenGL library support. V3D data can be loaded
and then interpreted into GL commands, suitable for GL display lists.

%description -l pl.UTF-8
Biblioteka libv3d to biblioteka wejścia-wyjścia dla formatu plików V3D
- plików modeli 3D generowanych przez modeler Vertex 3D Model
Assembler (stąd nazwa V3D). Służy do odczytu i zapisu danych V3D z/do
pliku i pamięci z obsługą biblioteki OpenGL. Dane V3D mogą być
wczytane i przekształcone na polecenia GL, odpowiednie dla list
wyświetlających.

%package devel
Summary:	LibV3D development headers
Summary(pl.UTF-8):	Pliki nagłówkowe LibV3D
Group:		Development/Libraries
Requires:	%{name} = %{version}-%{release}

%description devel
Header files for LibV3D library.

%description devel -l pl.UTF-8
Pliki nagłówkowe biblioteki LibV3D.

%prep
%setup -q
%patch0 -p1

%build
./configure Linux

%{__make} \
	CC="%{__cc}" \
	CPP="%{__cxx}" \
	CFLAGS="%{rpmcflags} -Wall %{!?debug:-fomit-frame-pointer} -ffast-math -D__USE_BSD" \
	LIB_DIRS=

%install
rm -rf $RPM_BUILD_ROOT

%{__make} install \
	PREFIX=$RPM_BUILD_ROOT%{_prefix} \
	LIB_DIR=$RPM_BUILD_ROOT%{_libdir} \
	MAN_DIR=$RPM_BUILD_ROOT%{_mandir}/man3

/sbin/ldconfig -n $RPM_BUILD_ROOT%{_libdir}

%clean
rm -rf $RPM_BUILD_ROOT

%post	-p /sbin/ldconfig
%postun	-p /sbin/ldconfig

%files
%defattr(644,root,root,755)
%doc AUTHORS README
%attr(755,root,root) %{_libdir}/libv3d.so.*.*.*
%attr(755,root,root) %ghost %{_libdir}/libv3d.so.0

%files devel
%defattr(644,root,root,755)
%attr(755,root,root) %{_libdir}/libv3d.so
%{_includedir}/v3d
%{_mandir}/man3/V3D*.3*
%{_mandir}/man3/v3d_*.3*
