Summary:	LibV3D
Summary(pl):	Biblioteka LibV3D
Name:		libv3d
Version:	0.1.14
Release:	1
License:	LGPL
Group:		X11/Library
Source0:	ftp://wolfpack.twu.net/users/wolfpack/%{name}-%{version}.tar.bz2
# Source0-md5:	c2b95a7f82a81b5a8b5987f6fee92b24
Patch0:		%{name}-soname.patch
URL:		http://wolfpack.twu.net/Vertex/libv3d.html
BuildRequires:	OpenGL-devel
Requires:	OpenGL
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%define		_noautoreqdep	libGL.so.1 libGLU.so.1

%description
The libv3d library is a IO library for the V3D file format, a 3D model
file generated by the modeller Vertex 3D Model Assembler (hence the
name V3D). It is used to read and write V3D data to/from file and
memory with integrated OpenGL library support. V3D data can be loaded
and then interpreted into GL commands, suitable for GL display lists.

%description -l pl
Biblioteka libv3d to biblioteka wej¶cia-wyj¶cia dla formatu plików
V3D - plików modeli 3D generowanych przez modeler Vertex 3D Model
Assembler (st±d nazwa V3D). S³u¿y do odczytu i zapisu danych V3D z/do
pliku i pamiêci z obs³ug± biblioteki OpenGL. Dane V3D mog± byæ
wczytane i przekszta³cone na polecenia GL, odpowiednie dla list
wy¶wietlaj±cych.

%package devel
Summary:	LibV3D development headers
Summary(pl):	Pliki nag³ówkowe LibV3D
Group:		Library/Development
Requires:	%{name} = %{version}-%{release}

%description devel
Header files for LibV3D library.

%description devel -l pl
Pliki nag³ówkowe biblioteki LibV3D.

%prep
%setup -q
%patch -p1

%build
./configure Linux

%{__make} \
	CC="%{__cc}" \
	CXX="%{__cxx}" \
	CFLAGS="%{rpmcflags} -Wall %{!?debug:-fomit-frame-pointer} -ffast-math -D__USE_BSD" \
	INC_DIRS="-I/usr/X11R6/include"

%install
rm -rf $RPM_BUILD_ROOT

%{__make} install \
	PREFIX=$RPM_BUILD_ROOT%{_prefix} \
	MAN_DIR=$RPM_BUILD_ROOT%{_mandir}/man3

%clean
rm -rf $RPM_BUILD_ROOT

%post	-p /sbin/ldconfig
%postun	-p /sbin/ldconfig

%files
%defattr(644,root,root,755)
%doc AUTHORS README
%attr(755,root,root) %{_libdir}/libv3d.so.*.*

%files devel
%defattr(644,root,root,755)
%attr(755,root,root) %{_libdir}/libv3d.so
%attr(644,root,root) %{_includedir}/v3d
%attr(644,root,root) %{_mandir}/man3/*
